modLoader = "javafml"
loaderVersion = "[45,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "smallships"
version = "${version}"
displayName = "Small Ships"
authors = "talhanation, metroite"
updateJSONURL="https://raw.githubusercontent.com/talhanation/smallships/main/update.json"
description = '''
This mod adds vanilla friendly ships into Minecraft!
'''
logoFile = "icon.png"

[[dependencies.smallships]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.smallships]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,)"
ordering = "NONE"
side = "BOTH"
